### ISSUE TITLE
Minor "Application name is not set" errors.

### ISSUE THREAD

**Issue by prefislt** [MaxMaeder/DriveBackupV2#1]
I'm getting some errors. Checking for a OneDrive credentials file but it's disabled because i'm using Google Drive.
![image](https://user-images.githubusercontent.com/1362964/82758737-0bde0400-9df1-11ea-8f52-a50945100566.png)

**Comment by MaxMaeder** [comment]
Hi, at least of right now, this is expected behavior. In the future, I probably should prevent this from happening by default.

To disable stacktraces like this one turn on the `suppress-errors` setting near the bottom of the `config.yml`.

**Comment by MaxMaeder** [comment]
@prefislt v1.1.0 will address this.
