### ISSUE TITLE
[Feature Request] SQL backup features

### ISSUE THREAD

**Issue by RalphORama** [MaxMaeder/DriveBackupV2#10]
## Exclude SQL tables by name

8 of my plugins use MySQL databases, but two generate a considerable amount of data I don't want to include in my backup.  The tables in particular are 

    co_block
    co_item

The ability to exclude SQL tables based on table name would be very beneficial.

## Rate limit SQL queries

Whenever a backup runs, it causes all other database connections on my server to time out as it pulls data over the network.  If rate limiting options for SQL could be implemented, that would be hugely beneficial

**Comment by MaxMaeder** [comment]
Excluding tables will be in the next release!

**Comment by MaxMaeder** [comment]
Feature added with a8dcad3351870ee1e5f495bb44d5326692c508cd.
