### ISSUE TITLE
Failed backup error but successfully back ups the saves

### ISSUE THREAD

**Issue by Dougarooski** [MaxMaeder/DriveBackupV2#101]
Have my server saving 10 saves to a google drive and deleting the oldest file. 
Every hour when it backups the saves, it spits out both an error saying it failed as well as the message backup complete. 
The error keeps getting spit out even though it is correctly deleting the oldest file in the google drive and saving a copy of the world. 
Not an actual issue, just seems to have some sort of catch that's coming up with false positives for failing to save.
![DriveBackup Error Code](https://user-images.githubusercontent.com/88568408/185713761-66b0cc39-e27a-418d-80b7-a1e69ed5f63f.png)
.

**Comment by rhld16** [comment]
Could you enable debug in config and send the resulting error log in order to further troubleshooting.

**Comment by rhld16** [comment]
No response for a while, please reopen if you encounter the issue again.
