### ISSUE TITLE
BUG: world default can't upload

### ISSUE THREAD

**Issue by CraftBlack** [MaxMaeder/DriveBackupV2#104]
### Describe the bug

world default can't upload

Error details:
https://hastebin.com/ovezagesit.log

config.yml [DriveBackupV2 1.6.0]:
https://hastebin.com/epexecoyar.yml
### To Reproduce

1. /drivebackup backup

2.
![Screenshot_1357](https://user-images.githubusercontent.com/80093376/187711757-27ac5e73-8900-4e16-8438-fb0ce127868f.png)

### Screenshots / Videos

None

### Server and Plugin Versions

Plugins (1): DriveBackupV2 1.6.0
This server is running Paper version git-Paper-135 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: eff22eb)

### Additional Context

None

**Comment by xiaofengv233** [comment]
+1

**Comment by lrmtheboss** [comment]
This should be fixed in the latest dev builds, If it happens again please let us know.
