### ISSUE TITLE
Can't backup files and blacklist not working

### ISSUE THREAD

**Issue by 1101-trash** [MaxMaeder/DriveBackupV2#105]
### Describe the bug

In my backup-list i have:
```
- glob: "*.json"
  format: "Backup-server-%FORMAT.zip"
  create: true

```
but it won't backup all files that are JSON. Not even one. I tried with "**/*.json", "./*.json"

And also can't make a backup of the root folder with the blacklist.
Although I have blacklisted 'cache' and 'libraries' they are still in the backup.
![image](https://user-images.githubusercontent.com/50521056/188509407-257b5a3f-9aba-4931-8fae-cd4b43386ab5.png)

### To Reproduce

Just editing the settings like above and running the backup.

**Comment by rhld16** [comment]
It is not possible to backup individual files. You can blacklist entire directories by appending '/**' e.g. ```- "libraries/**```

**Comment by 1101-trash** [comment]
> It is not possible to backup individual files. You can blacklist entire directories by appending '/**' e.g. `- "libraries/**`

Thanks you very much, I can handle that :)
