### ISSUE TITLE
Add rsync as a backup protocol

### ISSUE THREAD

**Issue by ja2ui0** [MaxMaeder/DriveBackupV2#109]
### What feature do you want to see added?

Title says it all. I'd like to use the same `rsyncd` destination I use for all my other backups at home as a destination for DriveBackupV2 as well.

### Are there any alternatives?

I've set up a vsftpd server just for DriveBackupV2 and it passes internal test and all manual ones, but fails backups. That's either a bug or a misconfiguration but either way is a separate issue. Rsync would be preferable.

**Comment by rhld16** [comment]
Rsync would be impractical since we'd have to compile binaries for all platforms, please join the discord if you still want support with your sftp server
