### ISSUE TITLE
Add a command that allows you to restore the backups that you create easily

### ISSUE THREAD

**Issue by nick123456789025** [MaxMaeder/DriveBackupV2#113]
I had an issue where this would have been really helpful due to how the server provider handles FTP. It would have been easier to just run a command in a new world than to wait for the zip file to slowly copy to my computer. This feature would be amazing for many people, not just me I'm sure.

**Comment by rhld16** [comment]
We currently don't have the time or resources to implement this feature, feel free to PR if you're able to.
