### ISSUE TITLE
FTP bug about "remote-save-directory"

### ISSUE THREAD

**Issue by poyu39** [MaxMaeder/DriveBackupV2#121]
### Describe the bug

i use ftp to bakup my server, and something is wrong about dir.
DriverBackup2 can create "root" folder for file, but it can't create remote-save-directory.
i open debug mode and test ftp, it still say successfull.

nas console log
![image](https://user-images.githubusercontent.com/42506064/214630535-14792ece-fe7e-449d-a518-1eafcba50c4b.png)

config
```
local-save-directory: "backups"
remote-save-directory: "/mnt/user/server/backup/lobby"
```

### To Reproduce

use /drivebackup backup or /drivebackup test ftp

### Server and Plugin Versions

![image](https://user-images.githubusercontent.com/42506064/214631643-9eb74b22-d084-40a0-b31a-06dd9a1eeafe.png)

**Comment by rhld16** [comment]
Check the ftpd logs to see why this is happening, it's mostly due to permission issues with the FTP user
