### ISSUE TITLE
"The next backup..." message in chat has the incorrect time of the next backup

### ISSUE THREAD

**Issue by CathalCraft** [MaxMaeder/DriveBackupV2#124]
When using scheduled backups that have different times set, the in-game message after a backup that says "The next backup is at <time> <date> <timezone>" shows the next time of the first schedule and not the second.

```java
scheduled-backups: true
backup-schedule-list:
- days: 
  - "everyday"
  time: "05:00"
- days: 
  - "everyday"
  time: "17:00"
``` 

For example, when the 05:00 backup completes, it says the next backup time is 05:00.
Then when the 17:00 backup completes, it says the next backup time is 17:00.
Is there a way to put multiple times on one schedule?

**Comment by abcde1477** [comment]
+1
