### ISSUE TITLE
Backups not uploaded to drive

### ISSUE THREAD

**Issue by nazmi** [MaxMaeder/DriveBackupV2#13]
>.... [10:09:28 INFO]: nazmoo issued server command: /drivebackup backup
>.... [10:09:28 INFO]: [DriveBackupV2] Creating backups, the server may lag for a little while...
>.... [10:09:28 INFO]: [DriveBackupV2] Doing backups for .
>.... [10:12:11 INFO]: [DriveBackupV2] Uploading file to Google Drive
>.... [10:12:13 WARN]: java.lang.NullPointerException
>.... [10:12:13 WARN]: at ratismal.drivebackup.googledrive.GoogleDriveUploader.uploadFile(GoogleDriveUploader.java:323)
>.... [10:12:13 WARN]: at ratismal.drivebackup.UploadThread.run(UploadThread.java:155)
>.... [10:12:13 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
>.... [10:12:13 INFO]: [DriveBackupV2] File uploaded in 1.59 seconds (1193728.3KB/s)
>.... [10:12:13 INFO]: [DriveBackupV2] Backup complete

Instruction followed from wiki.
Probably the best way to reproduce:
1. Relink account by 4 times (I switched server and try to figure why files are not uploaded to drive). 
2. Backuplist "." 

I will wait for scheduled upload and update here.

**Comment by MaxMaeder** [comment]
Can I see your `config.yml`? Also, what version of the plugin are you running? The latest stable version is 1.2.3.

**Comment by MaxMaeder** [comment]
You can only set the file path to backup to `.` in the new 1.3.0 beta. Try updating to [this](https://github.com/MaxMaeder/DriveBackupV2/releases/tag/v1.3.0-beta) version.

**Comment by nazmi** [comment]
>.... [10:08:00 INFO]: [DriveBackupV2] Enabling DriveBackupV2 v1.2.3*

Thanks for reminding to update. I was forced to believed this message.
>.... [10:08:19 INFO]: [DriveBackupV2] Hooray! You are running the latest release.

However, this version supports `.` I believed, by comparing two zips from v1.2.3 and  v1.3.0. They both are exactly same sizes
Seems like updating solve the Gdrive problem. Apreciated your help!
