### ISSUE TITLE
Update to 1.20.1 and 1.20.2

### ISSUE THREAD

**Issue by Shadowblitz16** [MaxMaeder/DriveBackupV2#135]
### What feature do you want to see added?

Title

### Are there any alternatives?

Yes but I can't figure them out.

**Comment by rhld16** [comment]
This plugin has supported every version since 1.8 without the need for any additional change, are there any specific errors you’ve encountered while attempting to use 1.20.X?

**Comment by Shadowblitz16** [comment]
> This plugin has supported every version since 1.8 without the need for any additional change, are there any specific errors you’ve encountered while attempting to use 1.20.X?

no I just saw that it didn't say for 1.20.1.
Maybe I should of tested it first.
