### ISSUE TITLE
Bug: Cannot read the array length because "<local6>" is null

### ISSUE THREAD

**Issue by paul-eff** [MaxMaeder/DriveBackupV2#136]
### Describe the bug

Whenever the plugin tries to backup (and delete old backups) I see the following error: [latest.log](https://github.com/MaxMaeder/DriveBackupV2/files/13065762/latest.log)
It seems like backup deletions fails, but from what I can see it does work as intended. Nevertheless, this error also shows when creating the first ever backup. Or e.g. creating the second backup but instructed to keep 16 before deleting.

### To Reproduce

1. Start server
2. Wait for scheduled or manual backup
3. See error

### Server and Plugin Versions

Plugin version: 1.6.1
Java version: 17.0.4
Server software: Paper
Server software version: git-Paper-245 (MC: 1.20.2)

### Additional Context

Other plugins I run: Dynmap, WorldEdit, AntiPoup

**Comment by lrmtheboss** [comment]
What value do you have for `local-save-directory:` in your config?

**Comment by lrmtheboss** [comment]
Closing as stale
