### ISSUE TITLE
Consider adding support for Backblaze B2 

### ISSUE THREAD

**Issue by kevle1** [MaxMaeder/DriveBackupV2#138]
### What feature do you want to see added?

Consider adding support for [Backblaze B2](https://www.backblaze.com/cloud-storage) (or even S3 APIs). 

### Are there any alternatives?

I have been using this plugin to create local backups, and a have written a bash script using [Restic](https://github.com/restic/restic) scheduled to push the backups to a Backblaze B2 bucket. 

It would of course be much easier if the plugin supports B2/ S3/ R2 object storage natively, but it's just a suggestion. I understand if you go in the route of not supporting more "enterprise" solutions to keep things simple for users.

**Comment by DLmass** [comment]
1+ on this

**Comment by lrmtheboss** [comment]
S3 API support has been added in the latest release v1.6.2. If you find issues with it and Backblaze feel free to open a new issue or contact us on Discord.
