### ISSUE TITLE
Google drive error 429

### ISSUE THREAD

**Issue by Electronik21** [MaxMaeder/DriveBackupV2#143]
### Describe the bug

This might not be something you can fix, but whenever it tries to upload the backup to google drive it fails with error 429 too many requests. The plugins folder works but all 3 of the world folders fail

### To Reproduce

1. Run `/drivebackup linkaccount googledrive`
2. Run `/drivebackup backup`
3. See error: `com.google.api.client.googleapis.json.GoogleJsonResponseException: 429 Too Many Requests`

### Screenshots / Videos

![image](https://github.com/MaxMaeder/DriveBackupV2/assets/85518515/46828893-98bc-47b9-a11d-05e0c3138f86)

### Server and Plugin Versions

Plugin version: 1.6.1
Java version: 21.0.1
Server software: Paper
Server software version: git-Paper-388 (MC: 1.20.4)

**Comment by lrmtheboss** [comment]
It appears your hosting provider's network has sent too many requests to Google's API  causing it to reject the request from your server. Likely you are using shared hosting without a dedicated IP address.
