### ISSUE TITLE
missing documentation for %FORMAT & %NAME

### ISSUE THREAD

**Issue by StillGreen-san** [MaxMaeder/DriveBackupV2#153]
[Specifying what to Backup](https://github.com/MaxMaeder/DriveBackupV2/wiki/Specifying-what-to-Backup#format) explains custom timestamps but does not mention `%FORMAT` or `%NAME`

**Comment by lrmtheboss** [comment]
Added explanation

**Comment by StillGreen-san** [comment]
the path equivalent example under [Specifying-what-to-Backup#glob](https://github.com/MaxMaeder/DriveBackupV2/wiki/Specifying-what-to-Backup#glob) is now incorrect because of the inclusion of `%NAME` in the glob format
it should now be

```diff
@@ -52,6 +52,6 @@
 - path: "world_nether"
-  format: "Backup-world-%FORMAT.zip"
+  format: "Backup-world_nether-%FORMAT.zip"
   create: true
 - path: "world_the_end"
-  format: "Backup-world-%FORMAT.zip"
+  format: "Backup-world_the_end-%FORMAT.zip"
   create: true
```
