### ISSUE TITLE
Using a shared GDrive

### ISSUE THREAD

**Issue by nate-moo** [MaxMaeder/DriveBackupV2#18]
I have a shared GDrive with all my friends for backups to our server. is there a way I can use that instead of my straight drive

**Comment by MaxMaeder** [comment]
Sorry about the late reply, I have been really busy with school recently.

I have tried to add shared Google Drive support in the past. It is not possible with the OAuth scopes the plugin requests.

Sorry about that.

**Comment by nate-moo** [comment]
ah its fine, thanks for your time anyway
