### ISSUE TITLE
[Bug] Some characters are not correctly loaded from intl.yml

### ISSUE THREAD

**Issue by chasyumen** [MaxMaeder/DriveBackupV2#188]
### Describe the bug

Japanese characters from intl.yml are filled with many ? characters

### To Reproduce

set ja.yml as intl.yml from #187

### Screenshots / Videos

https://imgur.com/a/JIsLzj2

### Server and Plugin Versions

Paper MC 1.21.1-17

### Logs

N/A

### Config

default

**Comment by rhld16** [comment]
Characters load correctly on all machines I have tested. The issue is likely due to a missing package on your machine.
