### ISSUE TITLE
[Bug] GDrive ACCESS_TOKEN_SCOPE_INSUFFICIENT

### ISSUE THREAD

**Issue by BlazeCodeDev** [MaxMaeder/DriveBackupV2#200]
### Describe the bug

ACCESS_TOKEN_SCOPE_INSUFFICIENT when trying to backup to a GDrive folder

### To Reproduce

1. Link account to Google
2. /drivebackup backup
3. "Failed to backup to Google Drive, verify all credentials are correct or diagnose the problem with /drivebackup test googledrive"
4. /drivebackup test googledrive
5. "[DriveBackupV2] The Google Drive test was unsuccessful, please check the config.yml"

### Server and Plugin Versions

- Paper 1.21.1
- DriveBackup V1.8.0

### Logs

https://mclo.gs/9RjSnVq

### Config

https://pastebin.com/EDca6geG

**Comment by rhld16** [comment]
Due to recent Google-related changes, we had to change how we authenticate Google Drive. If this is the first time backing up in a while, you might find you’ll need to relink your account through the “/drivebackup link googledrive” command.
