### ISSUE TITLE
world backup corrupt, player Inventory restored but building not restored 

### ISSUE THREAD

**Issue by ramboi234** [MaxMaeder/DriveBackupV2#27]
so today I play Minecraft with my friend after backup complete few minutes later server crashed, then I check world backup on my google drive I restore the world, but when I logged on, the world is still same as we started playing, but item inventory restored properly,only world building not restored

**Comment by MaxMaeder** [comment]
You probably configured the `backup-list` wrong. Here is an article describing [how to configure it](https://github.com/MaxMaeder/DriveBackupV2/wiki/Specifying-What-to-Backup).

**Comment by ramboi234** [comment]
my backup setting:

# 
# DriveBackupV2   -   by Max Maeder (MaxTheGinus)
delay: 60
backup-thread-priority: 0
keep-count: 10
local-keep-count: 0
zip-compression: -1
backups-require-players: true
scheduled-backups: false
schedule-timezone: -00:00
backup-format-timezone: -00:00
backup-list:
- path: world
  format: '''Backup-world-''yyyy-M-d--HH-mm''.zip'''
  create: true
- path: plugins
  format: '''Backup-plugins-''yyyy-M-d--HH-mm''.zip'''
  create: true
dir: backups
destination: backups
googledrive:
  enabled: true
  
  
  I don't think its wrong, because I never touch it
