### ISSUE TITLE
Different intervals to different backups

### ISSUE THREAD

**Issue by konglingmingkong** [MaxMaeder/DriveBackupV2#28]
I hope the plugin can add different intervals for different backups
example
Backup palyerdata interval is 5 minutes
Backup plugin data interval is 6 hours

Others
Can I transport  the plugin to www.mcbbs.net？

**Comment by MaxMaeder** [comment]
Not currently, no. If you want to PR, I will gladly merge though.

**Comment by MaxMaeder** [comment]
> .Others
> Can I transport the plugin to www.mcbbs.net？

No, please direct server owners to Bukkit or Spigot.
