### ISSUE TITLE
[FEATURE REQUEST] MySQL database backup? 

### ISSUE THREAD

**Issue by prefislt** [MaxMaeder/DriveBackupV2#3]
Databases are very important. Maybe you planning to implement MySQL database backup feature? That would be amazing.

**Comment by MaxMaeder** [comment]
Hi!

I believe databases are stored as files, so the current release of DriveBackupV2 should be able to back them up.

However, if you are storing them in a sub folder inside your Minecraft server directly and ONLY want to back up your databases, you can specify a path to the folder or each file with the 1.1.0 release.

I submitted the release for review on Bukkit last night, so it could take a few days to get approved. If you don’t want to wait, you can snag it from the releases tab of this GitHub.

Let me know if this fixes your problem,
Max

**Comment by prefislt** [comment]
Database is on dedicated MySQL server. So plugin will need to connect with MySQL database and dump everything from it to .sql file and then back it up.

**Comment by MaxMaeder** [comment]
I will try to add this in DriveBackupV2 v1.1.1.
