### ISSUE TITLE
New Feature - Custom Messages/Prefix

### ISSUE THREAD

**Issue by 0liverServers** [MaxMaeder/DriveBackupV2#4]
Amazing plugins, one request editing the messages to not show in-game only in console and the ability to change the prefix and messages of the plugin.

Thanks and keep up the great work!
Oliver

**Comment by MaxMaeder** [comment]
Great idea, I'll try to add a setting to disable in-game messages, as well as a setting to disable the prefix in the in-game messages in the 1.2.0 release.

Currently, you are able to change the messages sent out in-game at the bottom of the `config.yml`.

**Comment by MaxMaeder** [comment]
Feature added with commit 91d207ac44d98469d9b2b031a406c2aae9692847. Expect a release soon!

**Comment by 0liverServers** [comment]
Awesome, thanks!
