### ISSUE TITLE
Problem with backuping external mysql database. 

### ISSUE THREAD

**Issue by WarlordXZ** [MaxMaeder/DriveBackupV2#49]
this is my configuration: 
https://pastebin.pl/view/9e0bd6aa

the plugin successfully backup the database structure and the table structure but somehow failed to backup the data/ content inside the table

and when the server being backup, when its starting to backup my external MySQL server. There some error showed on my console

https://pastebin.pl/view/8fd84901

any clue about my problem?

**Comment by rhld16** [comment]
Fixed with #50
