### ISSUE TITLE
[Bug] "Connection closed without indication." With WasabiS3 in FTP

### ISSUE THREAD

**Issue by KaidenMikami** [MaxMaeder/DriveBackupV2#58]
Whenever I upload a backup, it gives me `ratismal.drivebackup.DriveBackup.lib.net.ftp.FTPConnectionClosedException: Connection closed without indication.` and subsequent backups gives me `java.net.SocketException: Broken pipe`. After going for a quick rundown on StackOverflow it's probably because the connection from Wasabi cuts off when it finishes uploading one file, while the plugin tries to stay with connection opened. Could be wrong, though.

Here are the logs from the attempt:

> ```drivebackup test ftp
> [07:01:53 INFO]: [DriveBackupV2] Beginning the (S)FTP connection and upload test
> [07:01:59 INFO]: [DriveBackupV2] The (S)FTP connection and upload test was successful
> drivebackup backup
> [07:02:07 INFO]: [DriveBackupV2] Forcing a backup
> [07:02:07 INFO]: Automatic saving is now disabled
> [07:02:07 INFO]: [DriveBackupV2] Criando backups, isso pode travar o servidor...
> [07:02:07 INFO]: [DriveBackupV2] Doing backups for "laid"
> [07:04:19 INFO]: [DriveBackupV2] Uploading file to (S)FTP
> [07:04:19 WARN]: ratismal.drivebackup.DriveBackup.lib.net.ftp.FTPConnectionClosedException: Connection closed without indication.
> [07:04:19 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.__getReply(FTP.java:317)
> [07:04:19 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.__getReply(FTP.java:294)
> [07:04:19 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:483)
> [07:04:19 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:608)
> [07:04:19 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.cwd(FTP.java:828)
> [07:04:19 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTPClient.changeWorkingDirectory(FTPClient.java:1128)
> [07:04:19 WARN]:        at ratismal.drivebackup.ftp.FTPUploader.createThenEnter(FTPUploader.java:338)
> [07:04:19 WARN]:        at ratismal.drivebackup.ftp.FTPUploader.uploadFile(FTPUploader.java:186)
> [07:04:19 WARN]:        at ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:305)
> [07:04:19 WARN]:        at ratismal.drivebackup.UploadThread.run(UploadThread.java:195)
> [07:04:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
> [07:04:19 INFO]: [DriveBackupV2] Upload failed
> [07:04:19 INFO]: [DriveBackupV2] There are 3 file(s) which exceeds the local limit of 2, deleting oldest
> [07:04:19 INFO]: [DriveBackupV2] Doing backups for "laid_nether"
> [07:04:54 INFO]: [DriveBackupV2] Uploading file to (S)FTP
> [07:04:54 WARN]: java.net.SocketException: Broken pipe
> [07:04:54 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
> [07:04:54 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
> [07:04:54 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
> [07:04:54 WARN]:        at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1045)
> [07:04:54 WARN]:        at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)
> [07:04:54 WARN]:        at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:321)
> [07:04:54 WARN]:        at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:325)
> [07:04:54 WARN]:        at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159)
> [07:04:54 WARN]:        at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248)
> [07:04:54 WARN]:        at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:257)
> [07:04:54 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.__send(FTP.java:505)
> [07:04:54 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:479)
> [07:04:54 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:608)
> [07:04:54 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.cwd(FTP.java:828)
> [07:04:54 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTPClient.changeWorkingDirectory(FTPClient.java:1128)
> [07:04:54 WARN]:        at ratismal.drivebackup.ftp.FTPUploader.resetWorkingDirectory(FTPUploader.java:349)
> [07:04:54 WARN]:        at ratismal.drivebackup.ftp.FTPUploader.uploadFile(FTPUploader.java:185)
> [07:04:54 WARN]:        at ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:305)
> [07:04:54 WARN]:        at ratismal.drivebackup.UploadThread.run(UploadThread.java:195)
> [07:04:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
> [07:04:54 INFO]: [DriveBackupV2] Upload failed
> [07:04:54 INFO]: [DriveBackupV2] There are 3 file(s) which exceeds the local limit of 2, deleting oldest
> [07:04:54 INFO]: [DriveBackupV2] Doing backups for "laid_the_end"
> [07:05:09 INFO]: [DriveBackupV2] Uploading file to (S)FTP
> [07:05:09 WARN]: java.net.SocketException: Broken pipe
> [07:05:09 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
> [07:05:09 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
> [07:05:09 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
> [07:05:09 WARN]:        at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1045)
> [07:05:09 WARN]:        at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)
> [07:05:09 WARN]:        at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:321)
> [07:05:09 WARN]:        at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:325)
> [07:05:09 WARN]:        at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159)
> [07:05:09 WARN]:        at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248)
> [07:05:09 WARN]:        at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:257)
> [07:05:09 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.__send(FTP.java:505)
> [07:05:09 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:479)
> [07:05:09 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:608)
> [07:05:09 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.cwd(FTP.java:828)
> [07:05:09 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTPClient.changeWorkingDirectory(FTPClient.java:1128)
> [07:05:09 WARN]:        at ratismal.drivebackup.ftp.FTPUploader.resetWorkingDirectory(FTPUploader.java:349)
> [07:05:09 WARN]:        at ratismal.drivebackup.ftp.FTPUploader.uploadFile(FTPUploader.java:185)
> [07:05:09 WARN]:        at ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:305)
> [07:05:09 WARN]:        at ratismal.drivebackup.UploadThread.run(UploadThread.java:195)
> [07:05:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
> [07:05:09 INFO]: [DriveBackupV2] Upload failed
> [07:05:09 INFO]: [DriveBackupV2] There are 3 file(s) which exceeds the local limit of 2, deleting oldest
> [07:05:09 INFO]: [DriveBackupV2] Doing backups for "plugins"
> [07:06:23 INFO]: [DriveBackupV2] Uploading file to (S)FTP
> [07:06:23 WARN]: java.net.SocketException: Broken pipe
> [07:06:23 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
> [07:06:23 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
> [07:06:23 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
> [07:06:23 WARN]:        at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1045)
> [07:06:23 WARN]:        at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)
> [07:06:23 WARN]:        at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:321)
> [07:06:23 WARN]:        at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:325)
> [07:06:23 WARN]:        at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159)
> [07:06:23 WARN]:        at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248)
> [07:06:23 WARN]:        at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:257)
> [07:06:23 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.__send(FTP.java:505)
> [07:06:23 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:479)
> [07:06:23 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:608)
> [07:06:23 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.cwd(FTP.java:828)
> [07:06:23 WARN]:        at ratismal.drivebackup.DriveBackup.lib.net.ftp.FTPClient.changeWorkingDirectory(FTPClient.java:1128)
> [07:06:23 WARN]:        at ratismal.drivebackup.ftp.FTPUploader.resetWorkingDirectory(FTPUploader.java:349)
> [07:06:23 WARN]:        at ratismal.drivebackup.ftp.FTPUploader.uploadFile(FTPUploader.java:185)
> [07:06:23 WARN]:        at ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:305)
> [07:06:23 WARN]:        at ratismal.drivebackup.UploadThread.run(UploadThread.java:195)
> [07:06:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
> [07:06:23 INFO]: [DriveBackupV2] Upload failed
> [07:06:23 INFO]: [DriveBackupV2] There are 3 file(s) which exceeds the local limit of 2, deleting oldest
> [07:06:23 INFO]: [DriveBackupV2] Local backup complete
> [07:06:24 INFO]: [DriveBackupV2] Failed to backup to the (S)FTP server, please check the server credentials in the config.yml
> [07:06:24 INFO]: [DriveBackupV2] Backup completo,
> [07:06:24 INFO]: Automatic saving is now enabled```

**Comment by rhld16** [comment]
Thank you for submitting a thorough issue - I will look into your issue later.

**Comment by KaidenMikami** [comment]
I've just joined your discord. Wasabi has a 30-day free trial with no credit card required if you want to debug it yourself.

**Comment by rhld16** [comment]
Closing this issue since #61 has a more encompassing objective
