### ISSUE TITLE
My backap "Exceeds local limit of 0"

### ISSUE THREAD

**Issue by ZoomGC** [MaxMaeder/DriveBackupV2#62]
I would like to know how to fix this, as I have a 200+GB File that I need to backup

**_01.08 18:31:19 [Server] INFO [DriveBackupV2] File uploaded in 175.9 seconds (33707.31KB/s)
01.08 18:31:19 [Server] INFO [DriveBackupV2] There are 1 file(s) which exceeds the local limit of 0, deleting oldest
01.08 18:31:19 [Server] INFO [DriveBackupV2] Doing backups for "plugins"
01.08 18:31:21 [Server] INFO [DriveBackupV2] Uploading file to Google Drive
01.08 18:31:25 [Server] INFO [DriveBackupV2] File uploaded in 3.77 seconds (9223.16KB/s)
01.08 18:31:25 [Server] INFO [DriveBackupV2] There are 1 file(s) which exceeds the local limit of 0, deleting oldest
01.08 18:31:25 [Server] INFO [DriveBackupV2] Doing backups for "Lostands"
01.08 18:31:25 [Server] INFO [DriveBackupV2] Uploading file to Google Drive
01.08 18:31:28 [Server] INFO [DriveBackupV2] File uploaded in 2.83 seconds (0KB/s)
01.08 18:31:28 [Server] INFO [DriveBackupV2] There are 1 file(s) which exceeds the local limit of 0, deleting oldest
01.08 18:31:28 [Server] INFO [DriveBackupV2] Doing backups for "LostLands_nether"_**

The first file and the second file seem to be fine but "LostLands" is only 22KB when it should be 150-230GB

Server Version = Paper 1.12.2
Plugin Version = DriveBackupV2-1.4.0

**Comment by rhld16** [comment]
The local limit message is normal behaviour depending on your config but the file uploading is obviously not. Would you be able to join [the discord](https://discord.gg/VdCAUtm) in order to make troubleshooting easier?

**Comment by rhld16** [comment]
This issue has been stale for almost two weeks, has it been resolved?

**Comment by rhld16** [comment]
Seeing no reply after several days, I will close this issue but if you still experience this issue then please open a new issue.
