### ISSUE TITLE
[Feature request] Exclude directory

### ISSUE THREAD

**Issue by Polsaker** [MaxMaeder/DriveBackupV2#63]
An example of this is if I want to backup the `plugins` directory, but I do not want to backup the `plugins/dynmap/web` directory (which is full of rendered tiles which make the final backup file huge)

**Comment by rhld16** [comment]
Take a look at https://github.com/MaxMaeder/DriveBackupV2/wiki/Specifying-What-to-Backup#blacklist to see how to blacklist certain files/directories from the backup
