### ISSUE TITLE
[Enhancement] Add 7z support

### ISSUE THREAD

**Issue by awesomemoder316** [MaxMaeder/DriveBackupV2#64]
What I suggest: Add option to use .7z instead of just .zip.
Rational: .7z has higher efficiency (compression wise, not time wise)
How it could be implemented: Add a toggle in the config.yml, and add the 7z zipping process in FileUtil#ZipIt()

**Comment by rhld16** [comment]
![image](https://user-images.githubusercontent.com/24809571/129947057-f6bda1c9-982b-4b0f-a70b-aa4a3e27a24d.png)
After some testing, as you can see above, I don't think there's enough of a benefit to warrant adding a new compression method.

**Comment by awesomemoder316** [comment]
That's fine, I understand.
