### ISSUE TITLE
[Severe] OneDrive Backup Broken ("Unverified")

### ISSUE THREAD

**Issue by ProfessorTox** [MaxMaeder/DriveBackupV2#65]
I'm not sure what server side changes you keep making, but they keep breaking functionality.

The application is now marked as "unverified", with the text "this app may be risky" on OneDrive, and because I am using an organizational account, there is no way to bypass this. The functionality is completely broken. I am unfortunately forced to look at a new backup system as a result.

**Comment by rhld16** [comment]
Oh no. We spent a lot of time over the past 2 months to get our Dropbox and Google Drive applications verified but we never realised it was needed for OneDrive since we don't use organizational accounts. We'll take a look at out options.

**Comment by rhld16** [comment]
After some research into the verification process it seems that we would need a company registration to even begin the process which, this project being simply a Minecraft plugin, is out of out scope.

**Comment by rhld16** [comment]
We may have a fix for this issue. Would you be willing to test the build?
