### ISSUE TITLE
[Severe] Google Drive Linking Broken

### ISSUE THREAD

**Issue by ProfessorTox** [MaxMaeder/DriveBackupV2#66]
Linking with the drivebackup.web.app application with Google Drive does not work. The code is entered successfully, but the plugin does not update or recognize that it has been paired. So, Google Drive backup functionality is completely broken.

**Comment by MaxMaeder** [comment]
Can you please join our Discord server so we can help you diagnose the problem. 

Keep in mind that the DriveBackup Authenticator (drivebackup.web.app) & corresponding version of the plugin are still in beta. The old method of authentication the stable release of the plugin uses should still work fine. 

Please also verify that you are not trying to authenticate using the DriveBackup Authenticator with the older stable plugin release as the Authenticator only works with the new beta release.
