### ISSUE TITLE
Color codes not parsing in messages

### ISSUE THREAD

**Issue by Raesak** [MaxMaeder/DriveBackupV2#69]
### Describe the bug

Color codes do not work in messages. Changing the color code in the "default-color" setting in the config.yml doesn't change anything. It uses the dark aqua color regardless.

Adding color codes directly to messages does not work as they don't get parsed.

Color codes in the prefix work completely fine though.

### To Reproduce

Add color codes anywhere.
Only parses in the prefix.

### Server and Plugin Versions

Minecraft: 1.17.1
Paper: 297
DriveBackupV2: 1.5.3

**Comment by rhld16** [comment]
Reproduced - will look into a solution soon

**Comment by rhld16** [comment]
Fixed in an upcoming build with a new MiniMessage version
