### ISSUE TITLE
Error when setting thread priority

### ISSUE THREAD

**Issue by prefislt** [MaxMaeder/DriveBackupV2#7]
If `backup-thread-priority:` set to lower number i getting this error message and backup doesn't work.

![image](https://user-images.githubusercontent.com/1362964/84677604-9ec51680-af37-11ea-8e51-83b2e3cb9d34.png)

>.... [15:38:28 WARN]: Exception in thread "Thread-160" java.lang.IllegalArgumentException
>.... [15:38:28 WARN]: at java.base/java.lang.Thread.setPriority(Thread.java:1141)
>.... [15:38:28 WARN]: at ratismal.drivebackup.UploadThread.run(UploadThread.java:54)
>.... [15:38:28 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by MaxMaeder** [comment]
Hi!

Are you running 1.2.0? In this version, I set the backup priority to the lowest possible value by default.

**Comment by prefislt** [comment]
Yes, make sense then. Negative value was left over from older version config.
It works fine with default value.

**Comment by MaxMaeder** [comment]
Great
