### ISSUE TITLE
Adding a few hours in one day for the backup

### ISSUE THREAD

**Issue by mrtajniak** [MaxMaeder/DriveBackupV2#76]
### What feature do you want to see added?

I miss the possibility of adding a few hours in which to perform a backup

**Comment by mrtajniak** [comment]
Because this:
```
backup-schedule-list:
- days:
   - "everyday"
   time:
   - "08:00"
   - "10:00"
   - "12:00"
   - "14:00"
   - "4:00 pm"
   - "18:00"
   - "20:00"
   - "22:00"
```
doesn't work for some reason

**Comment by rhld16** [comment]
Could you explain clearer what the issue is and how you think it could be resolved?

**Comment by mrtajniak** [comment]
> Could you explain clearer what the issue is and how you think it could be resolved?

For example I want to make backup everyday at 
8AM 10AM 12AM 2PM 4PM 8PM 10PM

**Comment by rhld16** [comment]
Are there any console messages to suggest why this isn't happening?

**Comment by mrtajniak** [comment]
> Are there any console messages to suggest why this isn't happening?

I don't know how to do this

**Comment by rhld16** [comment]
Please join our [Discord](https://discord.gg/VdCAUtm) so that we can further assist you
