### ISSUE TITLE
No backup method is enabled

### ISSUE THREAD

**Issue by mariusHSK05** [MaxMaeder/DriveBackupV2#8]
Hello everybody!
Here is my config:
`
delay: 30
backup-thread-priority: 1
keep-count: 20
local-keep-count: 20
backups-require-players: true

scheduled-backups: false
schedule-timezone: "-00:00"
backup-schedule-list:

backup-list:
- path: "../"
  format: "'ServerBackup-'dd-MM-yyyy_HH-mm.zip'"
  create: true
  blacklist:
  - "backups"
  - "crash-reports"
  - "logs"
  - "eula.txt"
  - "Redstoneworld.zip"
  - "server.jar"
  - "server.jar.old"
 

external-backup-list:

dir: "backups"

destination: "backups"

googledrive:
  enabled: false
onedrive:
  enabled: false
ftp:
  enabled: false
  hostname: "ftp.example.com"
  port: 21
  sftp: false
  ftps: false
  username: "Username"
  password: 
  sftp-public-key: 
  sftp-passphrase: 
  working-dir:

messages:
  send-in-chat: true
  no-perm: "Zugriff verweigert: Deine Rechte reichen für diesen Befehl nicht aus."
  backup-start: "Backup wird erstellt, der Server könnte kurz laggen..."
  backup-complete: "Backup vollständig,"
  next-backup: "das nächste Backup wird in %TIME Minuten ausgeführt."
  next-schedule-backup: "das nächste Backup findet am %DATE statt."
  next-schedule-backup-format: "dd.MM.yyyy, HH:mm"

advanced:
  metrics: true
  update-check: true
  suppress-errors: false
  prefix-chat-messages: true
  date-language: "de"
  ftp-file-seperator: "/"
`
I've configured it to create a backup of the entire server directory (except the blacklisted files) every 30 minutes. Just a local backup. But if I use /drivebackup backup it tells the that there is no backup method enabled.
Can someone help me? Thanks!
Greetings from germany, mariusHSK05

**Comment by MaxMaeder** [comment]
DriveBackupV2 is mainly meant to backup your data to an external location, such as Google Drive. As such, newer versions of DriveBackupV2 won’t let you just back up your files locally.

Right now, your best solution is to use an [older version of DriveBackupV2](https://github.com/MaxMaeder/DriveBackupV2/releases/tag/v1.2.1) that doesn’t do this. 

I’m planning on adding proper support for only creating local backups soon, so this workaround should only be temporary.

Remember to change `local-keep-count` in the `config.yml` to the number of backups you want to keep locally. It’s set to zero by default.

Let me know if this helps!

**Comment by mariusHSK05** [comment]
Thanks for your reply. Then I will need to connect my OneDrive account. I thought it's possible to create just a local backup, but if this is planned in future versions, everything's fine.
Thanks again!
~mariusHSK05
