### ISSUE TITLE
WebDAV unsuccessful with correct login credentials

### ISSUE THREAD

**Issue by TheRedHugo** [MaxMaeder/DriveBackupV2#80]
### Describe the bug

Hey,
when I try to test WebDAV using `/drivebackup test webdav` it always returns `The WebDAV test was unsuccessful, please check the config.yml`

### To Reproduce

`webdav:`
`  enabled: true`
`  hostname: "https://<WebDAV URL>:443"`
`  username: "<Username>"`
`  password: "<Password>"`

**Comment by coolman28129** [comment]
Try restarting your server after saving the config.yml

**Comment by rhld16** [comment]
Please ensure you have saved the config and reloaded the config using `/drivebackup reloadconfig`. Referring to WebDAV, are you running a NextCloud/ownCloud instance? Otherwise what WebDAV server are you running?

**Comment by TheRedHugo** [comment]
I've tried reloading and restarting.
I am using 1&1 IONOS HiDrive as WebDAV Storage and tried a WebDAV Client Application which seems to work.
I also installed ownCloud on my Web Server and tried using WebDAV as Backup Storage which didn't work either

**Comment by rhld16** [comment]
From what I can see HiDrive should work without problem. Are you using 'https://webdav.hidrive.strato.com/users/USER/' as the host? When you run `/drivebackup backup`, what errors are printed to console?

**Comment by TheRedHugo** [comment]
Thank you for your help,  it works now. The problem was that I only specified the host and not the user directory `/users/<Username>`

:D
