### ISSUE TITLE
Turn saving off only while compressing/copying the server files

### ISSUE THREAD

**Issue by mov51** [MaxMaeder/DriveBackupV2#87]
### What feature do you want to see added?

or turning saving back on while the backup is being uploaded to it's destination, to word it another way. 

The hope is to limit the amount of time that the server isn't able to save, especially for larger backups or slow destinations. 

### Are there any alternatives?

The compression part of the backup can be sped up/adjusted by changing the compression ratio, what you're backing up, and the thread priority, but the upload speed of the destination can cause a major bottle neck that leaves saving off for long enough to fill up the allocated ram of the server. 

I've tried to adjust each of those to limit the time that saving is off, but just uploading by 21gb world to Google Drive takes nearly 30 minutes on my server regardless of the host. Even ignoring Google Drive I'm not aware of a reason why saving would need to be off for the upload process, especially since that's likely to be completely out of the users control.

**Comment by rhld16** [comment]
Thanks for creating the issue - should be fixed now, try out the latest Actions build to confirm this.

**Comment by mov51** [comment]
That was fast! Just tested it out and it seems to work perfectly! The only odd thing is that it doesn't announce that saving is off/on, which threw me off at first. 
It looks like you move to a new way of changing that instead of sending the command directly. Not sure if that's something worth adding an output for, but it made me think that it wasn't tuning off at all at first. Otherwise that's exactly what I needed, thank you!

**Comment by rhld16** [comment]
I've always known this was possible but due to how the plugin is setup if I was to leave the setAutoSave method and just move it's the method call to happen during compression, the console would be sent the message for every backup file which could generate unneeded spam. Your suggestion of adding a message could be an ideal solution.

**Comment by mov51** [comment]
It just threw me off a bit as I was used to seeing the message. Knowing that saving is off/on is a nice bit of reassurance though.
