### ISSUE TITLE
Support for 1.5.2?

### ISSUE THREAD

**Issue by CrxckedDest0y3r** [MaxMaeder/DriveBackupV2#97]
### What feature do you want to see added?

I have a eagler client server, its a 1.5.2 server that can be played through a web browser, and most 1.5.2 plugins work with it, so I'm requesting you to make drive backup v2 for  1.5.2 please please please please

**Comment by rhld16** [comment]
1.5.2 is almost 10 years old so it would be impractial to support such legacy software
